import type { Checkpoint } from "@/lib/types";
import { CALL_KIT, DIGEST, F, triageFor } from "./shared";

const ids = (...list: string[]) => list;

const AT_0830 = ids("em-1", "em-2", "em-3", "em-4", "em-5", "em-6", "sl-0738", "sl-0805", "sl-0807", "sl-0822", "rd-1", "rd-2", "rd-3", "rd-4", "rd-5");
const AT_1005 = [...AT_0830, ...ids("em-7", "em-8", "em-9", "em-10", "em-11", "em-12", "em-13", "em-14", "em-15", "em-16", "sl-0958", "doc-davr-brief", "doc-q3-notes")];
const AT_1210 = [...AT_1005, ...ids("em-17", "em-18", "em-19", "em-20", "em-21", "em-22", "em-23", "em-24", "sl-1042", "sl-1147", "sl-1203", "sl-1205")];
const AT_1316 = [...AT_1210, ...ids("em-25", "em-26", "sl-1215", "sl-1316")];
const AT_1512 = [...AT_1316, ...ids("em-27", "em-28", "em-29", "sl-1350", "sl-1512")];

const DEC_DSA = {
  id: "dec-dsa",
  title: "Sign the Davr Data Sharing Agreement before the 10:30 call?",
  dueAt: "10:25",
  dueLabel: null,
  effortMin: 10,
  whyYou:
    "It needs your signature, Davr will ask about it on the call, and no customer data can move until it is signed.",
  options: [
    {
      id: "conditional",
      label: "Sign once legal confirms the CBU rules are covered",
      consequence:
        "New Central Bank of Uzbekistan guidance also requires a designated local data protection contact. Legal confirms both, then you sign.",
    },
    { id: "now", label: "Sign now", consequence: "Fastest, but the local data protection contact may still be missing." },
    { id: "later", label: "Commit to a date on the call", consequence: "Davr waits and the migration stays blocked." },
  ],
  recommendedOptionId: "conditional",
  risk: "high",
  sourceIds: ["em-2", "rd-1"],
} as const;

const PC_REORG = {
  id: "pc-reorg-move",
  eventId: "ev-reorg",
  action: "move",
  start: "11:45",
  end: "12:30",
  title: null,
  delegateTo: null,
  forDecisionId: null,
  reason: "Overlaps the Q3 close review. Starting after it keeps both.",
  message: { to: "priya", body: "Could we start the team structure follow-up at 11:45 instead of 11:20? Same length, no overlap." },
  sourceIds: ["ev-reorg", "ev-q3close"],
} as const;

const PC_SME = {
  id: "pc-sme-defer",
  eventId: "ev-sme",
  action: "defer",
  start: null,
  end: null,
  title: null,
  delegateTo: null,
  forDecisionId: null,
  reason: "It overlaps two other meetings and nothing in it is due today.",
  message: { to: "marcus", body: "Can we move the SME lending competitive review to tomorrow? Today's late morning is triple-booked. I'll still see you at 09:45." },
  sourceIds: ["ev-sme"],
} as const;

const DL_ONEPAGER = { id: "dl-onepager", at: "17:00", label: "One-pager due to Richard", hard: true, sourceIds: ["em-11"] };

export const SEED_CHECKPOINTS: Checkpoint[] = [
  {
    id: "0830",
    at: "08:30",
    label: "Morning brief",
    trigger: "Start of day",
    generatedBy: "seed",
    output: {
      headline:
        "Three things need you before 10:00. Your 10:30 Davr call has a regulatory dependency nobody has flagged.",
      decisions: [
        {
          id: "dec-cover",
          title: "Ask Maya to cover your scheduling today?",
          dueAt: "08:45",
          dueLabel: null,
          effortMin: 2,
          whyYou: "Your assistant is out sick. Only you can give someone access to your calendar.",
          options: [
            {
              id: "maya",
              label: "Ask Maya, with scoped access",
              consequence: "She sees your schedule and the tasks routed to her. Email bodies and board material stay private.",
            },
            { id: "self", label: "Manage it yourself", consequence: "Nobody tracks changes while you are in meetings." },
          ],
          recommendedOptionId: "maya",
          risk: "medium",
          sourceIds: ["sl-0738"],
        },
        { ...DEC_DSA, options: [...DEC_DSA.options], sourceIds: [...DEC_DSA.sourceIds] },
        {
          id: "dec-marcus",
          title: "Protect Marcus's 1:1 at 09:45?",
          dueAt: "09:45",
          dueLabel: null,
          effortMin: 1,
          whyYou: "He moved it again this morning, and the product review just before it can run over.",
          options: [
            { id: "keep", label: "Keep it; leave product review at 09:45", consequence: "Priya and Tom finish the review without you." },
            { id: "move", label: "Move it to tomorrow", consequence: "Another delay for a 1:1 that keeps slipping." },
          ],
          recommendedOptionId: "keep",
          risk: "low",
          sourceIds: ["sl-0822", "ev-marcus"],
        },
      ],
      delegations: [
        {
          id: "dlg-maya-cover",
          to: "maya",
          channel: "slack",
          subject: null,
          body: "Could you cover my scheduling today? Helm will show you my calendar and anything routed to you. Email bodies and board material stay private.",
          reason: "Your assistant is out sick",
          sourceIds: ["sl-0738"],
        },
        {
          id: "dlg-legal-dsa",
          to: "legal",
          channel: "email",
          subject: "DSA: two checks before I sign",
          body: "Before I sign the Davr DSA: is this the final version, and does it meet the Central Bank of Uzbekistan's new cross-border data guidance, including a designated local data protection contact? If yes to both by 10:25, I'll sign before the 10:30 call.",
          reason: "Your signature is the blocker, but the new CBU rules add a second requirement",
          sourceIds: ["em-2", "rd-1"],
        },
        {
          id: "dlg-maya-expenses",
          to: "maya",
          channel: "slack",
          subject: null,
          body: "Could you clear the three routine expense approvals waiting for me? Nothing unusual in them.",
          reason: "Routine, not worth your time today",
          sourceIds: ["em-5"],
        },
      ],
      planChanges: [
        {
          id: "pc-q3close-move",
          eventId: "ev-q3close",
          action: "move",
          start: "11:15",
          end: "11:45",
          title: null,
          delegateTo: null,
          forDecisionId: null,
          reason: "It starts before the Davr call ends.",
          message: { to: "sarah", body: "Can we start the Q3 close review at 11:15 and keep it to 30 minutes? I'm on the Davr call until then." },
          sourceIds: ["ev-q3close", "ev-davr"],
        },
        { ...PC_REORG, message: { ...PC_REORG.message }, sourceIds: [...PC_REORG.sourceIds] },
        { ...PC_SME, message: { ...PC_SME.message }, sourceIds: [...PC_SME.sourceIds] },
      ],
      briefs: [
        {
          eventId: "ev-boardprep",
          summary: "Richard and Sarah. Confirm which version of the board deck is current and who owns the Q3 numbers.",
          youDecide: ["Which deck version is final"],
          watchOut: [],
          sourceIds: ["ev-boardprep"],
        },
        {
          eventId: "ev-product",
          summary: "Priya and Tom. Tom flagged growing notification-system tech debt this morning; it is not blocking anything this week. Leave at 09:45 for Marcus.",
          youDecide: [],
          watchOut: ["Hard stop at 09:45"],
          sourceIds: ["sl-0805", "ev-product"],
        },
        {
          eventId: "ev-marcus",
          summary: "Marcus moved this 1:1 to 09:45. Keep it short and keep it.",
          youDecide: [],
          watchOut: [],
          sourceIds: ["sl-0822"],
        },
        {
          eventId: "ev-davr",
          summary: "Davr Bank leadership, Bekzod Nazarov and Dilnoza Rashidova, with interpreter Nodira. Legal says the DSA is still unsigned. An article in your reading backlog says new CBU guidance requires a signed DSA before any customer data crosses the border, plus a designated local data protection contact.",
          youDecide: ["Whether to sign the DSA before the call"],
          watchOut: ["Data migration needs both the DSA and a local data protection contact"],
          sourceIds: ["ev-davr", "em-2", "rd-1"],
        },
      ],
      facts: [],
      triage: triageFor(AT_0830),
      alerts: [
        {
          id: "al-cbu",
          kind: "hidden-dependency",
          title: "Your reading backlog changes the 10:30 call",
          detail: "Article 1 says banks acquiring Uzbek entities need a signed DSA before any customer data moves, and must designate a local data protection contact. Your DSA is unsigned, and nothing in your materials names a contact.",
          sourceIds: ["rd-1", "em-2"],
        },
        {
          id: "al-late-morning",
          kind: "conflict",
          title: "Late morning is triple-booked",
          detail: "Three meetings overlap each other and the Davr call. Helm proposes two moves and one deferral.",
          sourceIds: ["ev-davr", "ev-q3close", "ev-reorg", "ev-sme"],
        },
        {
          id: "al-assistant",
          kind: "risk",
          title: "Nobody is watching your calendar",
          detail: "Your assistant is out sick. Maya offered to help with coverage.",
          sourceIds: ["sl-0738"],
        },
      ],
      deadlines: [{ id: "dl-davr", at: "10:30", label: "Davr Day-1 call", hard: true, sourceIds: ["ev-davr"] }],
      callKit: null,
      digest: DIGEST,
    },
  },
  {
    id: "1005",
    at: "10:05",
    label: "Interpreter cancels",
    trigger: "em-16",
    generatedBy: "seed",
    output: {
      headline:
        "Your interpreter cancelled. Keep the 10:30 slot as an alignment call, and sign in writing later.",
      decisions: [
        {
          id: "dec-davr-mode",
          title: "Run the Davr call without an interpreter?",
          dueAt: "10:15",
          dueLabel: null,
          effortMin: 3,
          whyYou: "Only you can change the purpose of a call with the acquired bank's chairman.",
          options: [
            {
              id: "align",
              label: "Keep 10:30 as an alignment call",
              consequence: "Send a bilingual pre-read, ask Davr for a bilingual colleague, confirm each point in the chat, and sign in writing after legal review.",
            },
            {
              id: "postpone",
              label: "Postpone to tomorrow with an interpreter",
              consequence: "Cleaner, but Day-1 slips a day and Richard's investors ask about Davr tomorrow.",
            },
            {
              id: "signoff",
              label: "Go ahead with sign-off as planned",
              consequence: "Not recommended. Dilnoza relies on interpretation, the redline is unreviewed, governing law is open and Central Bank approval is pending.",
            },
          ],
          recommendedOptionId: "align",
          risk: "high",
          sourceIds: ["em-16", "doc-davr-brief", "em-7", "em-11"],
        },
        { ...DEC_DSA, options: [...DEC_DSA.options], sourceIds: ["em-2", "rd-1", "doc-davr-brief"] },
        {
          id: "dec-onepager-plan",
          title: "How should Richard's Q3 one-pager get made?",
          dueAt: "10:30",
          dueLabel: null,
          effortMin: 2,
          whyYou: "Richard asked you directly, it goes to investors tomorrow morning, and it is due at 17:00.",
          options: [
            {
              id: "helm",
              label: "Helm drafts, Sarah checks numbers, you approve",
              consequence: "A sourced draft exists now and updates as facts change. You review once, after the afternoon's corrections land.",
            },
            { id: "self", label: "Write it yourself after 16:30", consequence: "Thirty minutes before the deadline, with no time for checks." },
          ],
          recommendedOptionId: "helm",
          risk: "medium",
          sourceIds: ["em-11", "doc-q3-notes"],
        },
      ],
      delegations: [
        {
          id: "dlg-bekzod",
          to: "bekzod",
          channel: "email",
          subject: "Today's 10:30 call",
          body: "Dear Bekzod, our interpreter is unwell today. We would like to keep the 10:30 call to align on the open points, speak slowly, and confirm everything in writing afterwards in Uzbek and Russian. Could a bilingual colleague from your team join to help Dilnoza? A short pre-read with the agenda and key terms follows in a few minutes.",
          reason: "Davr can likely supply a bilingual colleague faster than anyone can find an interpreter",
          sourceIds: ["em-16", "doc-davr-brief"],
        },
        {
          id: "dlg-legal-redline",
          to: "legal",
          channel: "email",
          subject: "Dilnoza's redline: one page by 10:25",
          body: "Please send me a one-page summary of Dilnoza's 08:41 redline before the 10:30 call: what changed against our plan, what is still open (governing law), and anything we must not agree to out loud.",
          reason: "The redline has sat unreviewed since 08:41",
          sourceIds: ["em-7", "doc-davr-brief"],
        },
        {
          id: "dlg-sarah-numbers",
          to: "sarah",
          channel: "email",
          subject: "Q3 one-pager for Richard: numbers check by 15:30",
          body: "Richard wants a one-page Q3 summary by 17:00 for his investor meeting tomorrow. Helm has drafted it from deck v4 and the quarter's notes. Could you check the numbers by 15:30? In particular: NII up ~22% QoQ (QoQ or YoY, and is Davr consolidation in it?), cost-to-income 52%, and the $18M Davr capital split.",
          reason: "Sarah owns the numbers; investors will repeat them",
          sourceIds: ["em-11", "em-12", "doc-q3-notes"],
        },
      ],
      planChanges: [
        {
          id: "pc-davr-extend",
          eventId: "ev-davr",
          action: "extend",
          start: "10:30",
          end: "11:30",
          title: "Davr Bank: Day-1 alignment (no sign-off)",
          delegateTo: null,
          forDecisionId: null,
          reason: "Without an interpreter every point takes longer. Sign-off moves to writing.",
          message: null,
          sourceIds: ["em-16", "ev-davr"],
        },
        {
          id: "pc-q3close-delegate",
          eventId: "ev-q3close",
          action: "delegate",
          start: null,
          end: null,
          title: null,
          delegateTo: "sarah",
          forDecisionId: null,
          reason: "It now overlaps the longer Davr call. Sarah owns the numbers anyway; ask for five bullets and read them at lunch.",
          message: { to: "sarah", body: "I'll be on the Davr call until 11:30. Could you run the Q3 close review without me and send me five bullets? I'll read them at lunch." },
          sourceIds: ["ev-q3close", "ev-davr"],
        },
        { ...PC_REORG, message: { ...PC_REORG.message }, sourceIds: [...PC_REORG.sourceIds] },
        { ...PC_SME, message: { ...PC_SME.message }, sourceIds: [...PC_SME.sourceIds] },
      ],
      briefs: [
        {
          eventId: "ev-davr",
          summary: "Bekzod follows everyday English but struggles with fast legal and financial terms. Dilnoza has limited spoken English and usually relies on an interpreter. No interpreter today. Open: the DSA is unsigned on our side, Dilnoza's 08:41 redline is unreviewed, governing law is disputed, and Central Bank approval is pending.",
          youDecide: ["A signing date for the DSA", "Who leads a lawyer-to-lawyer call on governing law"],
          watchOut: [
            "Agree nothing binding out loud: governing law, tranche amounts, dates",
            "Data migration needs a signed DSA and a local data protection contact",
          ],
          sourceIds: ["doc-davr-brief", "em-7", "em-16", "rd-1"],
        },
        {
          eventId: "ev-reorg",
          summary: "Priya and the People team on last month's reorganisation of the digital banking teams.",
          youDecide: [],
          watchOut: [],
          sourceIds: ["ev-reorg"],
        },
      ],
      facts: [F.nii, F.costIncome, F.ai, F.acme, F.attrition, F.competition, F.techDebt, F.capital, F.dsa, F.callAtRisk, F.cbu],
      triage: triageFor(AT_1005),
      alerts: [
        {
          id: "al-premature",
          kind: "contradiction",
          title: "Sign-off was premature even with an interpreter",
          detail: "The DSA is unsigned, the redline is unreviewed, governing law is disputed and Central Bank approval is pending. None of these can be closed on this call.",
          sourceIds: ["doc-davr-brief", "em-7"],
        },
        {
          id: "al-investors",
          kind: "hidden-dependency",
          title: "Richard's one-pager goes to investors",
          detail: "He meets investors tomorrow morning. Anything in the one-pager will be repeated to them, so every line needs a source.",
          sourceIds: ["em-11", "em-15"],
        },
        {
          id: "al-overrun",
          kind: "risk",
          title: "Product review ran long again",
          detail: "Priya's review ran until about 09:58, into Marcus's 09:45 1:1.",
          sourceIds: ["sl-0958", "sl-0822"],
        },
      ],
      deadlines: [DL_ONEPAGER],
      callKit: CALL_KIT,
      digest: DIGEST,
    },
  },
  {
    id: "1210",
    at: "12:10",
    label: "Midday changes",
    trigger: "em-24",
    generatedBy: "seed",
    output: {
      headline:
        "TechCorp is staying and Acme is close. Richard wants Davr status in the one-pager. Comms is preparing a press statement for you.",
      decisions: [
        {
          id: "dec-dsa-today",
          title: "Sign the DSA today once legal confirms the CBU rules are covered?",
          dueAt: "17:00",
          dueLabel: null,
          effortMin: 5,
          whyYou: "Davr is now asking legal directly. Your signature is the only thing blocking the customer data migration.",
          options: [
            { id: "when-confirmed", label: "Sign as soon as legal confirms", consequence: "Davr gets it today if legal answers this afternoon." },
            { id: "now", label: "Sign now", consequence: "Ends the chase, but the local data protection contact may still be missing." },
          ],
          recommendedOptionId: "when-confirmed",
          risk: "high",
          sourceIds: ["em-18", "rd-1"],
        },
        {
          id: "dec-davr-followup",
          title: "Send the written summary of the Davr call",
          dueAt: "17:00",
          dueLabel: null,
          effortMin: 5,
          whyYou: "It is the record of what you and Davr's leadership agreed, in languages Dilnoza can read.",
          options: [
            { id: "after-legal", label: "Send after legal checks it", consequence: "A bilingual summary goes out today, with no binding terms." },
            { id: "now", label: "Send it now", consequence: "Faster, but legal hasn't seen it." },
          ],
          recommendedOptionId: "after-legal",
          risk: "medium",
          sourceIds: ["ev-davr", "em-7"],
        },
      ],
      delegations: [
        {
          id: "dlg-lena",
          to: "lena",
          channel: "slack",
          subject: null,
          body: "Great result on TechCorp. Could you lead the 15:30 as a short thank-you call? I'll join for the first ten minutes.",
          reason: "TechCorp confirmed it is staying",
          sourceIds: ["sl-1205", "ev-techcorp"],
        },
        {
          id: "dlg-jordan-ack",
          to: "jordan",
          channel: "slack",
          subject: null,
          body: "Thanks. Send the draft as soon as it's ready and I'll make time for it. Nothing goes out without my sign-off.",
          reason: "Comms is drafting a statement for your approval",
          sourceIds: ["sl-1203"],
        },
      ],
      planChanges: [
        {
          id: "pc-techcorp-shorten",
          eventId: "ev-techcorp",
          action: "shorten",
          start: "15:30",
          end: "15:45",
          title: "TechCorp: thank-you call (Lena leads)",
          delegateTo: null,
          forDecisionId: null,
          reason: "TechCorp confirmed it is staying. A full escalation hour is no longer needed.",
          message: { to: "lena", body: "Let's make the 15:30 a 15-minute thank-you call. You lead; I'll join for the first ten minutes." },
          sourceIds: ["sl-1205", "ev-techcorp"],
        },
        {
          id: "pc-onepager-block",
          eventId: null,
          action: "add",
          start: "15:45",
          end: "16:15",
          title: "Review and send Richard's one-pager",
          delegateTo: null,
          forDecisionId: "dec-onepager-send",
          reason: "Uses the time TechCorp no longer needs, after Sarah's 15:30 numbers check.",
          message: null,
          sourceIds: ["em-11", "em-24", "sl-1205"],
        },
      ],
      briefs: [
        {
          eventId: "ev-roundtable",
          summary: "Lunch roundtable with the branch managers.",
          youDecide: [],
          watchOut: [],
          sourceIds: ["ev-roundtable"],
        },
        {
          eventId: "ev-techcorp",
          summary: "Lena reports TechCorp is staying. Use the call to thank them and let Lena lead.",
          youDecide: [],
          watchOut: ["Don't reopen terms that Lena just settled"],
          sourceIds: ["sl-1205", "sl-1147"],
        },
      ],
      facts: [F.nii, F.costIncome, F.ai, F.acmeUpdated, F.techcorp, F.attritionUpdated, F.competition, F.techDebt, F.capital, F.dsa, F.callHeld, F.cbu],
      triage: triageFor(AT_1210),
      alerts: [
        {
          id: "al-press-early",
          kind: "risk",
          title: "A press statement is on its way to you",
          detail: "Jordan says a journalist inquiry is real and a draft is coming for your approval. Your afternoon is back to back, so Helm will find time when the draft lands.",
          sourceIds: ["sl-1203"],
        },
        {
          id: "al-techcorp-stale",
          kind: "stale",
          title: "The Q3 notes still list TechCorp as attrition",
          detail: "Lena confirmed at 12:05 that TechCorp is staying. The one-pager's risk line is updated.",
          sourceIds: ["sl-1205", "doc-q3-notes"],
        },
        {
          id: "al-acme",
          kind: "stale",
          title: "Acme moved from 'could close' to 'close to signing'",
          detail: "Marcus says legal redlines are back. It is still pipeline, not booked revenue.",
          sourceIds: ["sl-1042"],
        },
      ],
      deadlines: [DL_ONEPAGER],
      callKit: CALL_KIT,
      digest: DIGEST,
    },
  },
  {
    id: "1316",
    at: "13:16",
    label: "Press inquiry",
    trigger: "em-26",
    generatedBy: "seed",
    output: {
      headline:
        "A reporter wants comment on a layoffs rumor by 16:00, and comms needs your decision by about 15:00. Your afternoon is back to back.",
      decisions: [
        {
          id: "dec-press",
          title: "Approve the statement for TechInsight",
          dueAt: "15:00",
          dueLabel: null,
          effortMin: 10,
          whyYou: "It is a public statement about layoffs, attributed to the bank. The reporter's deadline is 16:00 and Jordan needs an hour.",
          options: [
            {
              id: "scoped",
              label: "Approve after a scope check",
              consequence: "The People team confirms 'no layoffs' also holds for Davr Bank staff. Jordan sends by 15:00 and cancels the default send.",
            },
            { id: "asis", label: "Approve as drafted", consequence: "Fastest. Risky if integration affects any Davr Bank roles." },
            { id: "decline", label: "Decline to comment", consequence: "The rumor runs unchallenged the night before Richard's investor meeting." },
          ],
          recommendedOptionId: "scoped",
          risk: "high",
          sourceIds: ["em-25", "em-26", "sl-1316", "em-23", "em-11"],
        },
        {
          id: "dec-dsa-today",
          title: "Sign the DSA today once legal confirms the CBU rules are covered?",
          dueAt: "17:00",
          dueLabel: null,
          effortMin: 5,
          whyYou: "Davr is now asking legal directly. Your signature is the only thing blocking the customer data migration.",
          options: [
            { id: "when-confirmed", label: "Sign as soon as legal confirms", consequence: "Davr gets it today if legal answers this afternoon." },
            { id: "now", label: "Sign now", consequence: "Ends the chase, but the local data protection contact may still be missing." },
          ],
          recommendedOptionId: "when-confirmed",
          risk: "high",
          sourceIds: ["em-18", "rd-1"],
        },
      ],
      delegations: [
        {
          id: "dlg-people-scope",
          to: "people",
          channel: "email",
          subject: "One-line check for a press statement",
          body: "We are about to say 'ABB Super Bank is not planning layoffs.' Can you confirm in one line that this holds for the whole group, including Davr Bank staff during integration? Needed by 14:30.",
          reason: "The statement's scope must be true group-wide",
          sourceIds: ["em-26", "em-23", "doc-davr-brief"],
        },
        {
          id: "dlg-jordan-approve",
          to: "jordan",
          channel: "slack",
          subject: null,
          body: "Approved, subject to the People team confirming it covers Davr Bank staff by 14:30. Please send it to Sam by 15:00, don't take the call, and cancel the 5pm default send.",
          reason: "Your approval, with the scope condition",
          sourceIds: ["em-26", "sl-1316"],
        },
        {
          id: "dlg-richard-headsup",
          to: "richard",
          channel: "email",
          subject: "Heads-up before tomorrow",
          body: "TechInsight is preparing a story claiming we plan to cut about 15% of staff. It isn't true: last month's reorganisation changed team structure, not headcount. We are issuing a statement today, and your one-pager will include it.",
          reason: "The story will likely run before his investor meeting",
          sourceIds: ["em-25", "em-23", "em-11"],
        },
      ],
      planChanges: [
        {
          id: "pc-roundtable-late",
          eventId: "ev-roundtable",
          action: "shorten",
          start: "13:30",
          end: "14:00",
          title: null,
          delegateTo: null,
          forDecisionId: null,
          reason: "Makes room for the press decision before the afternoon fills up.",
          message: { to: "maya", body: "Could you let the branch roundtable host know I'll join at 13:30?" },
          sourceIds: ["ev-roundtable", "sl-1316"],
        },
        {
          id: "pc-press-block",
          eventId: null,
          action: "add",
          start: "13:16",
          end: "13:30",
          title: "Decide: press statement",
          delegateTo: null,
          forDecisionId: "dec-press",
          reason: "The only realistic slot before Jordan's cut-off.",
          message: null,
          sourceIds: ["em-26", "sl-1316"],
        },
      ],
      briefs: [
        {
          eventId: "ev-vp-aisha",
          summary: "Aisha, VP Engineering candidate, CEO round. Priya's view should land before you start.",
          youDecide: ["Whether to support an offer this week"],
          watchOut: [],
          sourceIds: ["ev-vp-aisha"],
        },
      ],
      facts: [F.nii, F.costIncome, F.ai, F.acmeUpdated, F.techcorp, F.attritionUpdated, F.competition, F.techDebt, F.capital, F.dsa, F.callHeld, F.cbu, F.rumor, F.statementPending, F.itHeadcount],
      triage: triageFor(AT_1316),
      alerts: [
        {
          id: "al-default-send",
          kind: "contradiction",
          title: "Comms' fallback misses the deadline",
          detail: "Jordan said nothing goes out without your approval, but comms' process sends a final version at 5pm by default. That is an hour after the reporter's 4pm deadline.",
          sourceIds: ["sl-1203", "em-26", "em-25"],
        },
        {
          id: "al-investor-story",
          kind: "hidden-dependency",
          title: "The story will likely land before Richard's investors",
          detail: "Richard meets investors tomorrow morning. Add a press line to the one-pager and give him a heads-up today.",
          sourceIds: ["em-11", "em-25"],
        },
        {
          id: "al-scope",
          kind: "risk",
          title: "Check the statement's scope",
          detail: "The draft says the bank is not planning layoffs. The Davr integration includes a core banking migration and retention agreements for key staff, which implies not every Davr role is guaranteed. Confirm the line holds group-wide.",
          sourceIds: ["em-26", "doc-davr-brief"],
        },
      ],
      deadlines: [
        { id: "dl-press-jordan", at: "15:00", label: "Jordan needs the press decision", hard: false, sourceIds: ["sl-1316"] },
        { id: "dl-press", at: "16:00", label: "Reporter's deadline", hard: true, sourceIds: ["em-25"] },
        DL_ONEPAGER,
        { id: "dl-richard", at: "18:00", label: "Richard leaves for the airport", hard: true, sourceIds: ["sl-1215"] },
      ],
      callKit: CALL_KIT,
      digest: DIGEST,
    },
  },
  {
    id: "1512",
    at: "15:12",
    label: "CFO correction",
    trigger: "em-29",
    generatedBy: "seed",
    output: {
      headline:
        "Sarah corrected the Davr numbers and the terms have shifted. The one-pager is updated; legal must check the Davr lines before anything goes out in writing.",
      decisions: [
        {
          id: "dec-onepager-send",
          title: "Send Richard's one-pager",
          dueAt: "17:00",
          dueLabel: null,
          effortMin: 15,
          whyYou: "It goes to investors tomorrow under the board chair's name.",
          options: [
            {
              id: "review",
              label: "Review at 15:45, send by 16:15",
              consequence: "Uses the time TechCorp freed. Sarah's corrections are in; the Davr terms line is flagged as pending legal.",
            },
            {
              id: "wait-legal",
              label: "Wait for legal, send at 16:45",
              consequence: "Cleaner Davr wording, but less margin before Richard leaves around 18:00.",
            },
          ],
          recommendedOptionId: "review",
          risk: "high",
          sourceIds: ["em-11", "em-24", "em-29", "sl-1215"],
        },
        {
          id: "dec-dsa-hold",
          title: "Hold the DSA signature until legal checks the new terms?",
          dueAt: "17:00",
          dueLabel: null,
          effortMin: 2,
          whyYou: "Sarah says the terms shifted and to check with legal before finalising anything in writing. Your signature is writing.",
          options: [
            { id: "hold", label: "Hold until legal confirms", consequence: "Tell Davr it will be signed once legal confirms, likely tomorrow." },
            { id: "sign", label: "Sign today anyway", consequence: "Ends the chase, but the shift may touch the DSA." },
          ],
          recommendedOptionId: "hold",
          risk: "high",
          sourceIds: ["em-27", "em-28"],
        },
        {
          id: "dec-davr-followup",
          title: "Send the Davr summary once legal confirms the new terms",
          dueAt: "17:00",
          dueLabel: null,
          effortMin: 5,
          whyYou: "It is the written record for Davr's leadership, and the terms it describes have just moved.",
          options: [
            { id: "after-legal", label: "Send after legal checks it", consequence: "Goes out today or first thing tomorrow, accurate." },
            { id: "now", label: "Send it now", consequence: "Faster, but it may describe terms that no longer hold." },
          ],
          recommendedOptionId: "after-legal",
          risk: "medium",
          sourceIds: ["em-27", "ev-davr"],
        },
        {
          id: "dec-aisha",
          title: "Make Aisha an offer this week?",
          dueAt: null,
          dueLabel: "This week",
          effortMin: 5,
          whyYou: "It is a VP hire, and Priya wants to move this week.",
          options: [
            { id: "yes", label: "Yes, if your interview agreed", consequence: "Priya prepares the offer." },
            { id: "wait", label: "Wait for the second candidate's feedback", consequence: "Risks losing a candidate with excellent references." },
          ],
          recommendedOptionId: "yes",
          risk: "medium",
          sourceIds: ["sl-1350", "ev-vp-aisha"],
        },
      ],
      delegations: [
        {
          id: "dlg-legal-terms",
          to: "legal",
          channel: "email",
          subject: "What changed in the Davr terms?",
          body: "Sarah says the integration terms shifted since this morning's deck. By 15:40, in three lines: what changed, does it affect the DSA, and what can go in Richard's one-pager tonight?",
          reason: "Three things wait on this answer",
          sourceIds: ["em-27", "em-29"],
        },
        {
          id: "dlg-maya-status",
          to: "maya",
          channel: "slack",
          subject: null,
          body: "Richard's one-pager goes out by 16:15. If he asks before then, that's the plan.",
          reason: "Richard leaves around 18:00 and may ask Maya",
          sourceIds: ["sl-1215", "em-11"],
        },
      ],
      planChanges: [
        {
          id: "pc-onepager-block",
          eventId: null,
          action: "add",
          start: "15:45",
          end: "16:15",
          title: "Review and send Richard's one-pager",
          delegateTo: null,
          forDecisionId: "dec-onepager-send",
          reason: "Uses the time TechCorp no longer needs, after Sarah's correction.",
          message: null,
          sourceIds: ["em-11", "em-29"],
        },
      ],
      briefs: [],
      facts: [F.niiVerified, F.costIncomeVerified, F.ai, F.acmeUpdated, F.techcorp, F.attritionUpdated, F.competition, F.techDebt, F.capitalCorrected, F.terms, F.dsaHold, F.callHeld, F.cbu, F.rumor, F.statementApproved, F.itHeadcount],
      triage: triageFor(AT_1512),
      alerts: [
        {
          id: "al-capital",
          kind: "stale",
          title: "The Davr capital figure was wrong",
          detail: "This morning's deck said $18M. Sarah's correction: $18.6M, with $11.2M at Day-1 and $7.4M at Day-100. The one-pager now uses the corrected figures.",
          sourceIds: ["em-29", "em-12"],
        },
        {
          id: "al-terms",
          kind: "contradiction",
          title: "The Davr terms changed since the morning deck",
          detail: "Sarah: check with legal before finalising anything in writing. That covers the DSA signature, the Davr follow-up and the Davr lines in Richard's one-pager.",
          sourceIds: ["em-27"],
        },
        {
          id: "al-nii",
          kind: "stale",
          title: "NII growth includes Davr",
          detail: "Sarah confirms ~22% QoQ but says it includes Davr's first full quarter of consolidation, so say 'including Davr' externally.",
          sourceIds: ["em-29"],
        },
      ],
      deadlines: [
        { id: "dl-press", at: "16:00", label: "Reporter's deadline", hard: true, sourceIds: ["em-25"] },
        DL_ONEPAGER,
        { id: "dl-richard", at: "18:00", label: "Richard leaves for the airport", hard: true, sourceIds: ["sl-1215"] },
      ],
      callKit: CALL_KIT,
      digest: DIGEST,
    },
  },
];
